server:
  port: 9191

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sunglowsys_db
    username: postgres
    password: Password@123

  jpa:
    show_sql: true

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect


